[build]
    command = "npm run build" 
    publish = "" 

[[redirects]]
    from = "/users/tomsta/documents/github/intro-component-with-sign-up-form/sign-up-form/public/" 
    to = "/index.html" 
    status = 200 